### ISSUE TITLE
Can’t upload Team avatar

### ISSUE THREAD

**Issue by stursby** [nuxt-hub/feedback#1]
I'm trying to upload a Team avatar on `https://admin.hub.nuxt.com/{team_slug}/settings` but it seems to be failing.

Browser Console logs:

```
CflsP016.js:19 TypeError: Cannot read properties of undefined (reading 'files')
    at b (BUc5VUIV.js:1:4417)
    at Sn (CflsP016.js:19:38)
    at Pt (CflsP016.js:19:109)
    at hg (CflsP016.js:19:2180)
    at Proxy.E (C4sbyoA-.js:1:2995)
    at ie.onChange.n.<computed>.n.<computed> (C4sbyoA-.js:1:5228)
    at Sn (CflsP016.js:19:38)
    at Pt (CflsP016.js:19:109)
    at HTMLInputElement.n (CflsP016.js:23:8158)
```

The image I'm trying to upload is only `11kb` so I don't think that's the problem. (This is super low priority, but just wanted to let you know!)

**Comment by Atinux** [comment]
Should be fixed now @stursby 

Sorry about this, a regression from Nuxt UI 2.15.0!

**Comment by stursby** [comment]
No problem! Thanks for the fix. I can confirm it worked 🎉

<img width="72" alt="image" src="https://github.com/nuxt-hub/feedback/assets/527849/b2a6d3fa-7e7a-4b3b-b4ca-c0569de3a068">
